package dev.agenticscheduler.database.record

import androidx.room3.ColumnInfo
import androidx.room3.Entity
import androidx.room3.ForeignKey
import androidx.room3.Index
import androidx.room3.PrimaryKey

@Entity(tableName = "events") data class EventRecord(@PrimaryKey val id: String, val title: String, val flexibility: String, @ColumnInfo(name="pin_state") val pinState: String, @ColumnInfo(name="time_kind") val timeKind: String, @ColumnInfo(name="zoned_start_epoch_seconds") val zonedStartSeconds: Long?, @ColumnInfo(name="zoned_start_nanoseconds") val zonedStartNanos: Int?, @ColumnInfo(name="zoned_end_epoch_seconds") val zonedEndSeconds: Long?, @ColumnInfo(name="zoned_end_nanoseconds") val zonedEndNanos: Int?, @ColumnInfo(name="zoned_time_zone") val zonedTimeZone: String?, @ColumnInfo(name="all_day_start_date") val allDayStartDate: String?, @ColumnInfo(name="all_day_end_date_exclusive") val allDayEndDateExclusive: String?, @ColumnInfo(name="floating_start_local") val floatingStartLocal: String?, @ColumnInfo(name="floating_end_local_exclusive") val floatingEndLocalExclusive: String?)
@Entity(tableName = "tasks") data class TaskRecord(@PrimaryKey val id: String, val title: String, val status: String, val priority: String, @ColumnInfo(name="effort_estimated_iso") val effortEstimatedIso: String?, @ColumnInfo(name="effort_completed_iso") val effortCompletedIso: String, @ColumnInfo(name="effort_remaining_iso") val effortRemainingIso: String?, @ColumnInfo(name="deadline_kind") val deadlineKind: String?, @ColumnInfo(name="deadline_exact_epoch_seconds") val deadlineExactSeconds: Long?, @ColumnInfo(name="deadline_exact_nanoseconds") val deadlineExactNanos: Int?, @ColumnInfo(name="deadline_exact_time_zone") val deadlineTimeZone: String?, @ColumnInfo(name="deadline_date") val deadlineDate: String?, @ColumnInfo(name="deadline_policy") val deadlinePolicy: String?, @ColumnInfo(name="overflow_policy") val overflowPolicy: String?)
@Entity(tableName="focus_blocks", foreignKeys=[ForeignKey(entity=TaskRecord::class,parentColumns=["id"],childColumns=["task_id"],onDelete=ForeignKey.NO_ACTION)],indices=[Index("task_id")]) data class FocusBlockRecord(@PrimaryKey val id:String,@ColumnInfo(name="task_id") val taskId:String,@ColumnInfo(name="start_epoch_seconds") val startSeconds:Long,@ColumnInfo(name="start_nanoseconds") val startNanos:Int,@ColumnInfo(name="end_epoch_seconds") val endSeconds:Long,@ColumnInfo(name="end_nanoseconds") val endNanos:Int,@ColumnInfo(name="time_zone") val timeZone:String,val flexibility:String,@ColumnInfo(name="pin_state") val pinState:String)
@Entity(tableName="work_logs", foreignKeys=[ForeignKey(entity=TaskRecord::class,parentColumns=["id"],childColumns=["task_id"],onDelete=ForeignKey.NO_ACTION)],indices=[Index("task_id")]) data class WorkLogRecord(@PrimaryKey val id:String,@ColumnInfo(name="task_id") val taskId:String,@ColumnInfo(name="start_epoch_seconds") val startSeconds:Long,@ColumnInfo(name="start_nanoseconds") val startNanos:Int,@ColumnInfo(name="end_epoch_seconds") val endSeconds:Long,@ColumnInfo(name="end_nanoseconds") val endNanos:Int,@ColumnInfo(name="time_zone") val timeZone:String)
@Entity(tableName="task_dependencies",foreignKeys=[ForeignKey(entity=TaskRecord::class,parentColumns=["id"],childColumns=["prerequisite_task_id"],onDelete=ForeignKey.NO_ACTION),ForeignKey(entity=TaskRecord::class,parentColumns=["id"],childColumns=["dependent_task_id"],onDelete=ForeignKey.NO_ACTION)],indices=[Index("prerequisite_task_id"),Index("dependent_task_id"),Index(value=["prerequisite_task_id","dependent_task_id"],unique=true)]) data class TaskDependencyRecord(@PrimaryKey val id:String,@ColumnInfo(name="prerequisite_task_id") val prerequisiteTaskId:String,@ColumnInfo(name="dependent_task_id") val dependentTaskId:String)
@Entity(tableName="planning_profiles") data class PlanningProfileRecord(@PrimaryKey val id:String,val name:String)
@Entity(tableName="academic_years") data class AcademicYearRecord(@PrimaryKey val id:String,val name:String,@ColumnInfo(name="start_date") val startDate:String,@ColumnInfo(name="end_date_exclusive") val endDateExclusive:String)
@Entity(tableName="semesters",foreignKeys=[ForeignKey(entity=AcademicYearRecord::class,parentColumns=["id"],childColumns=["academic_year_id"],onDelete=ForeignKey.NO_ACTION)],indices=[Index("academic_year_id")]) data class SemesterRecord(@PrimaryKey val id:String,@ColumnInfo(name="academic_year_id") val academicYearId:String,val name:String,@ColumnInfo(name="start_date") val startDate:String,@ColumnInfo(name="end_date_exclusive") val endDateExclusive:String,@ColumnInfo(name="time_zone") val timeZone:String)
@Entity(tableName="academic_weeks",primaryKeys=["semester_id","week_number"],foreignKeys=[ForeignKey(entity=SemesterRecord::class,parentColumns=["id"],childColumns=["semester_id"],onDelete=ForeignKey.NO_ACTION)],indices=[Index("semester_id")]) data class AcademicWeekRecord(@ColumnInfo(name="semester_id") val semesterId:String,@ColumnInfo(name="week_number") val weekNumber:Int,@ColumnInfo(name="start_date") val startDate:String,@ColumnInfo(name="end_date_exclusive") val endDateExclusive:String)
@Entity(tableName="courses",foreignKeys=[ForeignKey(entity=SemesterRecord::class,parentColumns=["id"],childColumns=["semester_id"],onDelete=ForeignKey.NO_ACTION)],indices=[Index("semester_id")]) data class CourseRecord(@PrimaryKey val id:String,@ColumnInfo(name="semester_id") val semesterId:String,val name:String,val code:String?)
@Entity(tableName="period_templates") data class PeriodTemplateRecord(@PrimaryKey val id:String,val name:String)
@Entity(tableName="academic_periods",primaryKeys=["period_template_id","period_number"],foreignKeys=[ForeignKey(entity=PeriodTemplateRecord::class,parentColumns=["id"],childColumns=["period_template_id"],onDelete=ForeignKey.NO_ACTION)],indices=[Index("period_template_id")]) data class AcademicPeriodRecord(@ColumnInfo(name="period_template_id") val periodTemplateId:String,@ColumnInfo(name="period_number") val periodNumber:Int,@ColumnInfo(name="start_local_time") val startLocalTime:String,@ColumnInfo(name="end_local_time_exclusive") val endLocalTimeExclusive:String)
@Entity(tableName="course_schedule_rules",foreignKeys=[ForeignKey(entity=CourseRecord::class,parentColumns=["id"],childColumns=["course_id"],onDelete=ForeignKey.NO_ACTION),ForeignKey(entity=PeriodTemplateRecord::class,parentColumns=["id"],childColumns=["period_template_id"],onDelete=ForeignKey.NO_ACTION)],indices=[Index("course_id"),Index("period_template_id")]) data class CourseScheduleRuleRecord(@PrimaryKey val id:String,@ColumnInfo(name="course_id") val courseId:String,@ColumnInfo(name="day_of_week") val dayOfWeek:String,val room:String?,@ColumnInfo(name="time_kind") val timeKind:String,@ColumnInfo(name="clock_start_local_time") val clockStart:String?,@ColumnInfo(name="clock_end_local_time_exclusive") val clockEndExclusive:String?,@ColumnInfo(name="period_template_id") val periodTemplateId:String?,@ColumnInfo(name="start_period") val startPeriod:Int?,@ColumnInfo(name="end_period_inclusive") val endPeriodInclusive:Int?)
@Entity(tableName="course_rule_teaching_weeks",primaryKeys=["schedule_rule_id","week_number"],foreignKeys=[ForeignKey(entity=CourseScheduleRuleRecord::class,parentColumns=["id"],childColumns=["schedule_rule_id"],onDelete=ForeignKey.NO_ACTION)],indices=[Index("schedule_rule_id")]) data class CourseRuleWeekRecord(@ColumnInfo(name="schedule_rule_id") val scheduleRuleId:String,@ColumnInfo(name="week_number") val weekNumber:Int)
@Entity(tableName="academic_holidays",foreignKeys=[ForeignKey(entity=SemesterRecord::class,parentColumns=["id"],childColumns=["semester_id"],onDelete=ForeignKey.NO_ACTION)],indices=[Index("semester_id")]) data class AcademicHolidayRecord(@PrimaryKey val id:String,@ColumnInfo(name="semester_id") val semesterId:String,val name:String,@ColumnInfo(name="start_date") val startDate:String,@ColumnInfo(name="end_date_exclusive") val endDateExclusive:String,@ColumnInfo(name="teaching_effect") val teachingEffect:String)
@Entity(tableName="course_occurrence_exceptions",foreignKeys=[ForeignKey(entity=CourseScheduleRuleRecord::class,parentColumns=["id"],childColumns=["schedule_rule_id"],onDelete=ForeignKey.NO_ACTION)],indices=[Index("schedule_rule_id"),Index(value=["schedule_rule_id","academic_week_number"],unique=true)]) data class CourseOccurrenceExceptionRecord(@PrimaryKey val id:String,@ColumnInfo(name="schedule_rule_id") val scheduleRuleId:String,@ColumnInfo(name="academic_week_number") val academicWeekNumber:Int,val disposition:String,@ColumnInfo(name="time_override_start_epoch_seconds") val startSeconds:Long?,@ColumnInfo(name="time_override_start_nanoseconds") val startNanos:Int?,@ColumnInfo(name="time_override_end_epoch_seconds") val endSeconds:Long?,@ColumnInfo(name="time_override_end_nanoseconds") val endNanos:Int?,@ColumnInfo(name="time_override_time_zone") val timeZone:String?,@ColumnInfo(name="room_override_kind") val roomOverrideKind:String,@ColumnInfo(name="room_override_value") val roomOverrideValue:String?)
@Entity(tableName="exams",foreignKeys=[ForeignKey(entity=SemesterRecord::class,parentColumns=["id"],childColumns=["semester_id"],onDelete=ForeignKey.NO_ACTION),ForeignKey(entity=CourseRecord::class,parentColumns=["id"],childColumns=["course_id"],onDelete=ForeignKey.NO_ACTION)],indices=[Index("semester_id"),Index("course_id")]) data class ExamRecord(@PrimaryKey val id:String,@ColumnInfo(name="semester_id") val semesterId:String,@ColumnInfo(name="course_id") val courseId:String?,val title:String,@ColumnInfo(name="schedule_kind") val scheduleKind:String,@ColumnInfo(name="schedule_date") val scheduleDate:String?,@ColumnInfo(name="exact_start_epoch_seconds") val startSeconds:Long?,@ColumnInfo(name="exact_start_nanoseconds") val startNanos:Int?,@ColumnInfo(name="exact_end_epoch_seconds") val endSeconds:Long?,@ColumnInfo(name="exact_end_nanoseconds") val endNanos:Int?,@ColumnInfo(name="exact_time_zone") val timeZone:String?)
