package dev.agenticscheduler.database.dao

import androidx.room3.Dao
import androidx.room3.Query
import androidx.room3.Upsert
import dev.agenticscheduler.database.record.*
import kotlinx.coroutines.flow.Flow

@Dao interface EventDao { @Query("SELECT * FROM events ORDER BY id ASC") fun observeAll(): Flow<List<EventRecord>>; @Query("SELECT * FROM events WHERE id = :id") suspend fun get(id: String): EventRecord?; @Upsert suspend fun upsert(value: EventRecord) }
@Dao interface TaskDao { @Query("SELECT * FROM tasks ORDER BY id ASC") fun observeAll(): Flow<List<TaskRecord>>; @Query("SELECT * FROM tasks WHERE id = :id") suspend fun get(id: String): TaskRecord?; @Upsert suspend fun upsert(value: TaskRecord) }
@Dao interface FocusBlockDao { @Query("SELECT * FROM focus_blocks ORDER BY id ASC") fun observeAll(): Flow<List<FocusBlockRecord>>; @Query("SELECT * FROM focus_blocks WHERE id = :id") suspend fun get(id: String): FocusBlockRecord?; @Upsert suspend fun upsert(value: FocusBlockRecord); @Query("DELETE FROM focus_blocks WHERE id = :id") suspend fun delete(id:String) }
@Dao interface WorkLogDao { @Query("SELECT * FROM work_logs ORDER BY id ASC") fun observeAll(): Flow<List<WorkLogRecord>>; @Query("SELECT * FROM work_logs WHERE id = :id") suspend fun get(id: String): WorkLogRecord?; @Upsert suspend fun upsert(value: WorkLogRecord) }
@Dao interface TaskDependencyDao { @Query("SELECT * FROM task_dependencies ORDER BY id ASC") fun observeAll(): Flow<List<TaskDependencyRecord>>; @Query("SELECT * FROM task_dependencies WHERE id = :id") suspend fun get(id: String): TaskDependencyRecord?; @Query("SELECT id FROM task_dependencies WHERE prerequisite_task_id = :prerequisiteTaskId AND dependent_task_id = :dependentTaskId") suspend fun idForPair(prerequisiteTaskId: String, dependentTaskId: String): String?; @Upsert suspend fun upsert(value: TaskDependencyRecord) }
@Dao interface PlanningProfileDao { @Query("SELECT * FROM planning_profiles ORDER BY id ASC") fun observeAll(): Flow<List<PlanningProfileRecord>>; @Query("SELECT * FROM planning_profile_availability_windows ORDER BY planning_profile_id ASC, day_of_week ASC, start_local_time ASC, end_local_time_exclusive ASC") fun observeAllWindows(): Flow<List<PlanningProfileAvailabilityWindowRecord>>; @Query("SELECT * FROM planning_profiles WHERE id = :id") suspend fun get(id: String): PlanningProfileRecord?; @Query("SELECT * FROM planning_profile_availability_windows WHERE planning_profile_id=:id ORDER BY day_of_week ASC,start_local_time ASC,end_local_time_exclusive ASC") suspend fun windows(id:String):List<PlanningProfileAvailabilityWindowRecord>; @Upsert suspend fun upsert(value: PlanningProfileRecord); @Upsert suspend fun upsertWindows(values:List<PlanningProfileAvailabilityWindowRecord>); @Query("DELETE FROM planning_profile_availability_windows WHERE planning_profile_id=:id") suspend fun deleteWindows(id:String) }

@Dao interface AcademicYearDao { @Query("SELECT * FROM academic_years ORDER BY id ASC") fun observeAll(): Flow<List<AcademicYearRecord>>; @Query("SELECT * FROM academic_years WHERE id = :id") suspend fun get(id: String): AcademicYearRecord?; @Upsert suspend fun upsert(value: AcademicYearRecord) }
@Dao interface SemesterDao { @Query("SELECT * FROM semesters ORDER BY id ASC") fun observeAll(): Flow<List<SemesterRecord>>; @Query("SELECT * FROM academic_weeks ORDER BY semester_id ASC, week_number ASC") fun observeAllWeeks(): Flow<List<AcademicWeekRecord>>; @Query("SELECT * FROM semesters WHERE id = :id") suspend fun get(id: String): SemesterRecord?; @Query("SELECT * FROM academic_weeks WHERE semester_id = :semesterId ORDER BY week_number ASC") suspend fun weeks(semesterId: String): List<AcademicWeekRecord>; @Upsert suspend fun upsert(value: SemesterRecord); @Upsert suspend fun upsertWeeks(values: List<AcademicWeekRecord>); @Query("DELETE FROM academic_weeks WHERE semester_id = :semesterId") suspend fun deleteWeeks(semesterId: String) }
@Dao interface CourseDao { @Query("SELECT * FROM courses ORDER BY id ASC") fun observeAll(): Flow<List<CourseRecord>>; @Query("SELECT * FROM courses WHERE id = :id") suspend fun get(id: String): CourseRecord?; @Upsert suspend fun upsert(value: CourseRecord) }
@Dao interface PeriodTemplateDao { @Query("SELECT * FROM period_templates ORDER BY id ASC") fun observeAll(): Flow<List<PeriodTemplateRecord>>; @Query("SELECT * FROM academic_periods ORDER BY period_template_id ASC, period_number ASC") fun observeAllPeriods(): Flow<List<AcademicPeriodRecord>>; @Query("SELECT * FROM period_templates WHERE id = :id") suspend fun get(id: String): PeriodTemplateRecord?; @Query("SELECT * FROM academic_periods WHERE period_template_id = :templateId ORDER BY period_number ASC") suspend fun periods(templateId: String): List<AcademicPeriodRecord>; @Upsert suspend fun upsert(value: PeriodTemplateRecord); @Upsert suspend fun upsertPeriods(values: List<AcademicPeriodRecord>); @Query("DELETE FROM academic_periods WHERE period_template_id = :templateId") suspend fun deletePeriods(templateId: String) }
@Dao interface CourseScheduleRuleDao { @Query("SELECT * FROM course_schedule_rules ORDER BY id ASC") fun observeAll(): Flow<List<CourseScheduleRuleRecord>>; @Query("SELECT * FROM course_rule_teaching_weeks ORDER BY schedule_rule_id ASC, week_number ASC") fun observeAllWeeks(): Flow<List<CourseRuleWeekRecord>>; @Query("SELECT * FROM course_schedule_rules WHERE id = :id") suspend fun get(id: String): CourseScheduleRuleRecord?; @Query("SELECT * FROM course_rule_teaching_weeks WHERE schedule_rule_id = :id ORDER BY week_number ASC") suspend fun weeks(id: String): List<CourseRuleWeekRecord>; @Upsert suspend fun upsert(value: CourseScheduleRuleRecord); @Upsert suspend fun upsertWeeks(values: List<CourseRuleWeekRecord>); @Query("DELETE FROM course_rule_teaching_weeks WHERE schedule_rule_id = :id") suspend fun deleteWeeks(id: String) }
@Dao interface AcademicHolidayDao { @Query("SELECT * FROM academic_holidays ORDER BY id ASC") fun observeAll(): Flow<List<AcademicHolidayRecord>>; @Query("SELECT * FROM academic_holidays WHERE id = :id") suspend fun get(id: String): AcademicHolidayRecord?; @Upsert suspend fun upsert(value: AcademicHolidayRecord) }
@Dao interface CourseOccurrenceExceptionDao { @Query("SELECT * FROM course_occurrence_exceptions ORDER BY id ASC") fun observeAll(): Flow<List<CourseOccurrenceExceptionRecord>>; @Query("SELECT * FROM course_occurrence_exceptions WHERE id = :id") suspend fun get(id: String): CourseOccurrenceExceptionRecord?; @Query("SELECT id FROM course_occurrence_exceptions WHERE schedule_rule_id = :scheduleRuleId AND academic_week_number = :academicWeekNumber") suspend fun idForOccurrence(scheduleRuleId: String, academicWeekNumber: Int): String?; @Upsert suspend fun upsert(value: CourseOccurrenceExceptionRecord) }
@Dao interface ExamDao { @Query("SELECT * FROM exams ORDER BY id ASC") fun observeAll(): Flow<List<ExamRecord>>; @Query("SELECT * FROM exams WHERE id = :id") suspend fun get(id: String): ExamRecord?; @Upsert suspend fun upsert(value: ExamRecord) }
